### ISSUE TITLE
How to convert m4a to mp3 file

### ISSUE THREAD

**Issue by saurabhjain6853** [lixing123/ExtAudioConverter#3]
I have not found, How to convert m4a to mp3 file
I have got a error:
**the file format and data format pair is not valid**

**Comment by lixing123** [comment]
what's your outputFileType and outputFormatID?
maybe you can checkout here:
https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/SupportedAudioFormatsMacOSX/SupportedAudioFormatsMacOSX.html

**Comment by saurabhjain6853** [comment]
This is my code:

```
converter = [[ExtAudioConverter alloc] init];
    converter.outputSampleRate = 44100;
    converter.outputNumberChannels = 2;
    converter.outputBitDepth = BitDepth_16;
    converter.outputFormatID = kAudioFormatLinearPCM;
    converter.outputFileType = kAudioFileMP3Type;
```
And I use this here:

```
 converter.inputFile = [pathComponents.firstObject stringByAppendingPathComponent:@"MyAudioMemo.m4a"];
    converter.outputFile = [pathComponents.firstObject stringByAppendingPathComponent:@"MyAudioMemo.mp3"];
    [converter convert];
```
But it give the following Error:
**the file format and data format pair is not valid**

**Comment by lixing123** [comment]
your file format is mp3, but data format is linear pcm, this is invalid because mp3 file format can only contains mp3 data format.
do you want to convert the audio to mp3 file format? if so, change outputFormatID to kAudioFormatMPEGLayer3.

**Comment by saurabhjain6853** [comment]
Thank you, It's Working :)
